  CITY[m
  COURSES[m
  DASHBOARD[m
* [32mDEPLOY[m
  DEVELOP[m
  EnableUUID[m
  FASH_MESSAGE[m
  FRIENDLY[m
  Field_Validates[m
  HELP[m
  HOME[m
  HOME_CONFIG[m
  LEVEL[m
  MATERIAL[m
  MEMBERSHIP[m
  MEMBERSHIP-CUSTOM[m
  MEMBERSHIP-SIGNED[m
  SCHOOL[m
  SIGN_IN_PARAMETERS[m
  STYLES[m
  USER-PROFIL[m
  exercices[m
  main[m
  profil[m
